# Generated by Django 5.0.7 on 2024-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0002_booked_created_by_payments_created_by_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='out',
            field=models.BooleanField(default=False),
        ),
    ]
