# Generated by Django 5.0.7 on 2024-08-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0005_booked_aldults_booked_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='aldults',
            new_name='adult',
        ),
    ]
