# Generated by Django 5.0.7 on 2024-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0007_alter_payments_amount_due_alter_payments_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='updated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
