# Generated by Django 5.0.7 on 2024-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0008_alter_payments_updated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
