# Generated by Django 5.0.7 on 2024-08-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0012_services_alter_service_request_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
