# Generated by Django 5.0.7 on 2024-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0015_reservation_comply_reservationpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='display1',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
        migrations.AddField(
            model_name='info',
            name='display2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
