# Generated by Django 5.0.7 on 2024-08-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsys', '0016_info_display1_info_display2'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
